_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 19
                - 23
                - 55
            "4": 3.12.10
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 32
dataset:
    value: ../CleanData/Training - ImageWeakLabelling
